services:
  web:
    image: ghcr.io/alexandernorup/interactivecodeexecution:v1
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    privileged: true # Required for mounting docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    